### ISSUE TITLE
Support for new extended tweets

### ISSUE THREAD

**Issue by TomSteer** [abjerner/Skybrud.Social.Twitter#1]
Hey, I've noticed recently that images attached to a tweet weren't always getting returned in the Entities object. From doing a quick search it looks like it's down to the new extended tweets feature. I've pasted some links below on what I've found so far.

https://twittercommunity.com/t/some-tweets-are-not-returning-media-entity/74979
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets
https://twittercommunity.com/t/new-attachment-url-option-is-now-live-on-the-tweet-endpoints/74270

Cheers, Tom

**Comment by abjerner** [comment]
Thanks for reporting :D

The Twitter API documentation doesn't seems to be fully updated at the moment, but I will look into adding support for this ;)

**Comment by FabioRLeite** [comment]
how i can retrieve email user?

**Comment by abjerner** [comment]
@FabioRLeite Please create a new issue rather than posting a comment in an unrelated issue.

Anyways, you can read more about getting the email address here (which is only possible for the authenticated user):

http://social.skybrud.dk/twitter/endpoints/account/getting-information-about-the-authenticated-user/

**Comment by abjerner** [comment]
@TomSteer support for this was added a few releases ago, but seems I've missed posting an update here.

Usage would be something like:

```
foreach (TwitterMediaEntity media in tweet.ExtendedEntities.Media)
 {
    <h5>@media.DisplayUrl</h5>
    foreach (var size in media.Sizes)
    {
        <pre>@size.Alias => @size.Width x @size.Height</pre>
        <img src="@(media.MediaUrlHttps + ":" + @size.Alias)" alt=""/>
    }
}
```

Also, you can use `tweet.HasExtendedEntities` to check whether the tweet in fact has extended entities (or really whether they were included in the API response).
