### ISSUE TITLE
TwitterStatusMessage.Text not set in Extended mode

### ISSUE THREAD

**Issue by EvanMulawski** [abjerner/Skybrud.Social.Twitter#4]
When using `TwitterTweetMode.Extended`, `full_text` in the JSON response is not mapped to `TwitterStatusMessage.Text`. (Or is this mode not fully supported yet?)

https://github.com/abjerner/Skybrud.Social.Twitter/blob/97a2967f0ef44f840f98d831a808f848b5e4964c/src/Skybrud.Social.Twitter/Models/Statuses/TwitterStatusMessage.cs#L98

**Comment by abjerner** [comment]
@EvanMulawski Thanks a lot for reporting 👍 

That is an oversight. I will look into pushing a fix ;)

Meanwhile, you can access the full text through `tweet.JObject.GetString("full_text")`.

**Comment by EvanMulawski** [comment]
Thanks! This is my current workaround:

```
foreach (var statusMessage in statuses.Body)
{
    statusMessage.GetType().GetProperty(nameof(statusMessage.Text)).SetValue(statusMessage, statusMessage.JObject.Value<string>("full_text"), null);
}
```

**Comment by abjerner** [comment]
@EvanMulawski I pushed a new release yesterday, which adds the `FullText` property.

Twitter's feature with extended tweets is implemented a bit weird in the way that `text` is omitted in the JSON for extended tweets, similar to how the `full_text` property is omitted when not using extended mode.

For the models in Skybrud.Social, I'm trying to follow the JSON structure, so similarly the `Text` property will be null in Skybrud.Social when using extended mode.

Usage would therefore be something like:

```
if (tweet.HasFullText)
{
    <pre>@tweet.FullText</pre>
}
else
{
    <pre>@tweet.Text</pre>
}
```

or something like:

```
<pre>@(tweet.FullText ?? tweet.Text)</pre>
```
